-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.dim_date
(
    date_key integer NOT NULL,
    full_date date NOT NULL,
    year_int integer,
    quarter_name character varying(10) COLLATE pg_catalog."default",
    month_int integer,
    month_name character varying(20) COLLATE pg_catalog."default",
    week_number integer,
    day_of_week character varying(20) COLLATE pg_catalog."default",
    day_number integer,
    is_weekend boolean,
    is_holiday boolean,
    season character varying(20) COLLATE pg_catalog."default",
    is_winter boolean,
    is_flu_season boolean,
    CONSTRAINT dim_date_pkey PRIMARY KEY (date_key),
    CONSTRAINT dim_date_full_date_key UNIQUE (full_date)
);

CREATE TABLE IF NOT EXISTS public.dim_department
(
    department_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    department_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    type character varying(50) COLLATE pg_catalog."default",
    icu_capable boolean,
    CONSTRAINT dim_department_pkey PRIMARY KEY (department_id),
    CONSTRAINT dim_department_department_name_key UNIQUE (department_name)
);

CREATE TABLE IF NOT EXISTS public.dim_diagnosis
(
    diagnosis_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    category character varying(100) COLLATE pg_catalog."default" NOT NULL,
    icd_chapter character varying(100) COLLATE pg_catalog."default" NOT NULL,
    severity_weight numeric(5, 2),
    icu_probability numeric(5, 2),
    avg_los_hours integer,
    readmission_risk character varying(20) COLLATE pg_catalog."default",
    cost_weight numeric(6, 2),
    CONSTRAINT dim_diagnosis_pkey PRIMARY KEY (diagnosis_id)
);

CREATE TABLE IF NOT EXISTS public.dim_doctor
(
    doctor_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    doctor_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    specialty character varying(100) COLLATE pg_catalog."default" NOT NULL,
    grade character varying(50) COLLATE pg_catalog."default",
    years_experience integer,
    primary_hospital_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    annual_salary numeric(12, 2),
    part_time_flag boolean,
    burnout_baseline numeric(5, 2),
    CONSTRAINT dim_doctor_pkey PRIMARY KEY (doctor_id)
);

CREATE TABLE IF NOT EXISTS public.dim_hospital
(
    hospital_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    hospital_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    archetype character varying(100) COLLATE pg_catalog."default",
    nhs_trust_type character varying(100) COLLATE pg_catalog."default",
    region_id character varying(20) COLLATE pg_catalog."default",
    city character varying(100) COLLATE pg_catalog."default",
    beds integer,
    icu_beds integer,
    ed_bays integer,
    annual_budget_m numeric(12, 2),
    staff_fte integer,
    founding_year integer,
    teaching_hospital boolean,
    trauma_level integer,
    private_int boolean,
    avg_daily_admissions_base integer,
    satisfaction_base integer,
    efficiency_score numeric(5, 2),
    cost_index numeric(6, 2),
    readmission_rate_base numeric(5, 2),
    staffing_stress character varying(50) COLLATE pg_catalog."default",
    growth_trend numeric(8, 4),
    quality_trend numeric(8, 4),
    special_profile character varying(255) COLLATE pg_catalog."default",
    latitude numeric(10, 6),
    longitude numeric(10, 6),
    total_beds integer,
    CONSTRAINT dim_hospital_pkey PRIMARY KEY (hospital_id)
);

CREATE TABLE IF NOT EXISTS public.dim_patient
(
    patient_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    age integer,
    gender character varying(20) COLLATE pg_catalog."default",
    insurance_type character varying(50) COLLATE pg_catalog."default",
    chronic_conditions text COLLATE pg_catalog."default",
    chronic_condition_count integer,
    risk_category character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT dim_patient_pkey PRIMARY KEY (patient_id)
);

CREATE TABLE IF NOT EXISTS public.dim_region
(
    region_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    region_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    population_m numeric(10, 2),
    urban_rural character varying(20) COLLATE pg_catalog."default",
    avg_income_k integer,
    elderly_pct numeric(5, 2),
    poverty_rate numeric(5, 2),
    CONSTRAINT dim_region_pkey PRIMARY KEY (region_id)
);

CREATE TABLE IF NOT EXISTS public.fact_financials
(
    financial_record_id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    hospital_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    year_int integer,
    month_name integer,
    visit_count integer,
    operational_cost numeric(14, 2),
    staffing_cost numeric(14, 2),
    emergency_department_cost numeric(14, 2),
    icu_cost numeric(14, 2),
    revenue numeric(14, 2),
    profit_margin numeric(6, 2),
    government_funding numeric(14, 2),
    equipment_investment numeric(14, 2),
    expansion_projects_flag boolean,
    bed_occupancy_rate numeric(5, 2),
    avg_patient_satisfaction numeric(5, 2),
    readmission_rate numeric(5, 2),
    complaint_rate numeric(5, 2),
    mortality_rate numeric(5, 2),
    avg_wait_time_minutes numeric(10, 2),
    total_overtime_hours numeric(12, 2),
    avg_burnout_index numeric(5, 2),
    total_staff_absences integer,
    hospital_name character varying(150) COLLATE pg_catalog."default",
    latitude numeric(10, 6),
    longitude numeric(10, 6),
    CONSTRAINT fact_financials_pkey PRIMARY KEY (financial_record_id)
);

CREATE TABLE IF NOT EXISTS public.fact_patient_visits
(
    visit_id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    patient_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    hospital_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    department_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    doctor_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    arrival_datetime timestamp without time zone NOT NULL,
    triage_datetime timestamp without time zone,
    treatment_start_datetime timestamp without time zone,
    discharge_datetime timestamp without time zone,
    admission_type character varying(50) COLLATE pg_catalog."default",
    severity_level integer,
    diagnosis_category character varying(100) COLLATE pg_catalog."default",
    length_of_stay_hours numeric(10, 2),
    wait_time_minutes numeric(10, 2),
    treatment_delay_minutes integer,
    icu_required_flag boolean,
    outcome character varying(50) COLLATE pg_catalog."default",
    mortality_flag boolean,
    readmission_30_days_flag boolean,
    insurance_type character varying(50) COLLATE pg_catalog."default",
    treatment_cost numeric(12, 2),
    revenue_amount numeric(12, 2),
    satisfaction_score numeric(5, 2),
    complaint_flag boolean,
    ambulance_arrival_flag boolean,
    month_name integer,
    hospital_name character varying(150) COLLATE pg_catalog."default",
    latitude numeric(10, 6),
    longitude numeric(10, 6),
    CONSTRAINT fact_patient_visits_pkey PRIMARY KEY (visit_id)
);

CREATE TABLE IF NOT EXISTS public.fact_staffing
(
    shift_id character varying(30) COLLATE pg_catalog."default" NOT NULL,
    hospital_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    department_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    shift_date date NOT NULL,
    shift_type character varying(20) COLLATE pg_catalog."default",
    doctors_on_duty integer,
    nurses_on_duty integer,
    support_staff_count integer,
    staff_absence_count integer,
    overtime_hours numeric(10, 2),
    staff_cost numeric(12, 2),
    burnout_risk_index numeric(5, 2),
    month_name integer,
    hospital_name character varying(150) COLLATE pg_catalog."default",
    latitude numeric(10, 6),
    longitude numeric(10, 6),
    CONSTRAINT fact_staffing_pkey PRIMARY KEY (shift_id)
);
END;